# === Shared config ===
[teensy_base]
platform = teensy
framework = arduino
monitor_speed = 115200
lib_ldf_mode = chain+
lib_deps =
    jgromes/RadioLib@7.6.0
build_flags =
    -Iinclude
    -Ilib/telemetry
    -Iinclude/commands
    -Iinclude/configs
    -Iinclude/core
    -Iinclude/datastore
    -Iinclude/variant
    -Iinclude/radios
    -std=c++17

[teensy41_base]
board = teensy41
lib_deps =
    ${teensy_base.lib_deps}
    knolleary/PubSubClient@2.8
    ssilverman/QNEthernet
    ArduinoJson
build_flags =
    ${teensy_base.build_flags}
    -DTEENSY=41

[teensy40_base]
board = teensy40
lib_deps = 
    ${teensy_base.lib_deps}
build_flags =
    ${teensy_base.build_flags}
    -DTEENSY=40
# === Teensy 4,0 legacy variants ===
[env:teensy40_testing]
platform = ${teensy_base.platform}
framework = ${teensy_base.framework}
monitor_speed = ${teensy_base.monitor_speed}
lib_ldf_mode = ${teensy_base.lib_ldf_mode}
board = ${teensy40_base.board}
lib_deps = ${teensy40_base.lib_deps}
build_flags =
    ${teensy40_base.build_flags}
    -DDEVICE_VARIANT_TESTING

# === Teensy 4.1 standard variants ===

# Ground Station Radio at the Control Station
[env:GS_Control_Station]
platform = ${teensy_base.platform}
framework = ${teensy_base.framework}
monitor_speed = ${teensy_base.monitor_speed}
lib_ldf_mode = ${teensy_base.lib_ldf_mode}
board = ${teensy41_base.board}
lib_deps = ${teensy41_base.lib_deps}
build_flags =
    ${teensy41_base.build_flags}
    -DDEVICE_VARIANT_GROUNDSTATION
    -DGROUNDSTATION_LOCATION_CONTROLSTATION
    -DGS_ETHERNET_ENABLE

# Ground Station Radio at the Pad
[env:GS_PAD]
platform = ${teensy_base.platform}
framework = ${teensy_base.framework}
monitor_speed = ${teensy_base.monitor_speed}
lib_ldf_mode = ${teensy_base.lib_ldf_mode}
board = ${teensy41_base.board}
lib_deps = ${teensy41_base.lib_deps}
build_flags =
    ${teensy41_base.build_flags}
    -DDEVICE_VARIANT_GROUNDSTATION
    -DGROUNDSTATION_LOCATION_PAD
    -DGS_ETHERNET_ENABLE

#Flight Computer Variant, the radio pretends to be the FC 
# emits telemetry and responds to acks 
# TODO need to gate ethernet, stuff, and make this available on 4.0 and 4.1
[env:FC]
platform = ${teensy_base.platform}
framework = ${teensy_base.framework}
monitor_speed = ${teensy_base.monitor_speed}
lib_ldf_mode = ${teensy_base.lib_ldf_mode}
board = ${teensy41_base.board}
lib_deps = ${teensy_base.lib_deps}
build_flags =
    ${teensy41_base.build_flags}
    -DDEVICE_VARIANT_FLIGHTCOMPUTER

#Range testing mode, with serial logs in csv, and eth disabled